/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.onstream.android.games.gameoflife;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int light_blue=0x7f040000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int btnReset=0x7f070005;
        public static final int btnStart=0x7f070003;
        public static final int btnStop=0x7f070004;
        public static final int buttonsLayout=0x7f070002;
        public static final int imageViewLayout=0x7f070007;
        public static final int lblInfo=0x7f070006;
        public static final int lblMain=0x7f070001;
        public static final int mainView=0x7f070000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int alive=0x7f050003;
        public static final int app_name=0x7f050000;
        public static final int btnReset=0x7f050006;
        public static final int btnStart=0x7f050004;
        public static final int btnStop=0x7f050005;
        public static final int dead=0x7f050002;
        public static final int generation=0x7f050001;
    }
    public static final class style {
        public static final int MyDefaultTextAppearance=0x7f060002;
        public static final int MyTextView=0x7f060001;
        public static final int MyTheme=0x7f060000;
    }
}
